# Generated by Django 4.2.13 on 2024-05-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contact_alter_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
